"""empty message

Revision ID: fbda3a0f78b2
Revises: 898bcdb02c37
Create Date: 2024-11-20 17:14:17.212984

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fbda3a0f78b2"
down_revision: Union[str, None] = "898bcdb02c37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_position_path", table_name="structure", postgresql_using="gist")
    op.create_index(
        "ix_structure_path",
        "structure",
        ["path"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_structure_path", table_name="structure", postgresql_using="gist")
    op.create_index(
        "ix_position_path", "structure", ["path"], unique=False, postgresql_using="gist"
    )
    # ### end Alembic commands ###
