"""del phone

Revision ID: a9f25100bcf0
Revises: 7fcc6fe5279d
Create Date: 2024-11-05 17:43:06.923428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f25100bcf0'
down_revision: Union[str, None] = '7fcc6fe5279d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_phone_number_key', 'user', type_='unique')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_phone_number_key', 'user', ['phone_number'])
    # ### end Alembic commands ###
